# Generated by Django 4.0.5 on 2022-06-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_order_order_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length='250')),
                ('base_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.base')),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pizzatopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pizza')),
                ('topping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.topping')),
            ],
        ),
        migrations.CreateModel(
            name='pizzaorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('pizza_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.size'),
        ),
    ]
