# Generated by Django 4.0.5 on 2022-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pizza_topping_id_alter_pizza_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='quantity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
